apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hpa-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hpa
    spec:
      containers:
        - name: hello
          image: "k8s.gcr.io/hpa-example"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 0.5
